---
fail_fast: false
repos:
  - repo: https://github.com/onedr0p/sops-pre-commit
    rev: v2.1.1
    hooks:
      - id: forbid-secrets
        exclude: volsync.yaml
  - repo: https://github.com/oxsecurity/megalinter
    rev: v7.0.0
    hooks:
      - id: megalinter-incremental # Faster, less thorough
