---
# yaml-language-server: $schema=https://kubernetes-schemas.minuette.horse/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: "${APP}-volsync"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-css

  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        RESTIC_REPOSITORY: "{{ .SECRET_RESTIC_REPOSITORY_BASE }}/${APP}"
        RESTIC_PASSWORD: "{{ .SECRET_RESTIC_PASSWORD }}"
        AWS_ACCESS_KEY_ID: "{{ .SECRET_RESTIC_ACCESS_KEY_ID }}"
        AWS_SECRET_ACCESS_KEY: "{{ .SECRET_RESTIC_SECRET_ACCESS_KEY }}"
  dataFrom:
    - find:
        name:
          regexp: .*
      rewrite:
        - regexp:
            source: "(.*)"
            target: "$1"
---
# yaml-language-server: $schema=https://kubernetes-schemas.minuette.horse/volsync.backube/replicationdestination_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: "${APP}-bootstrap"
spec:
  trigger:
    manual: restore-once
  restic:
    repository: "${APP}-volsync"
    copyMethod: Snapshot
    volumeSnapshotClassName: "${VOLSYNC_SNAPSHOTCLASS:-csi-ceph-blockpool}"
    cacheStorageClassName: "${VOLSYNC_CACHE_SNAPSHOTCLASS:-openebs-hostpath}"
    cacheAccessModes: ["${VOLSYNC_CACHE_ACCESSMODES:-ReadWriteOnce}"]
    cacheCapacity: "${VOLSYNC_CACHE_CAPACITY:-8Gi}"
    storageClassName: "${VOLSYNC_STORAGECLASS:-rook-ceph-block}"
    accessModes: ["${VOLSYNC_ACCESSMODES:-ReadWriteOnce}"]
    moverSecurityContext:
      runAsUser: "${VOLSYNC_UID:-568}"
      runAsGroup: "${VOLSYNC_GID:-568}"
      fsGroup: "${VOLSYNC_GID:-568}"
    capacity: "${VOLSYNC_CAPACITY}"
    enableFileDeletion: true
    cleanupCachePVC: true
    cleanupTempPVC: true
---
# yaml-language-server: $schema=https://kubernetes-schemas.minuette.horse/volsync.backube/replicationsource_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: "${APP}"
spec:
  sourcePVC: "${CLAIM:-${APP}}"
  trigger:
    schedule: "0 * * * *"
  restic:
    copyMethod: "${VOLSYNC_COPYMETHOD:-Snapshot}"
    pruneIntervalDays: 10
    repository: "${APP}-volsync"
    volumeSnapshotClassName: "${VOLSYNC_SNAPSHOTCLASS:-csi-ceph-blockpool}"
    cacheCapacity: "${VOLSYNC_CACHE_CAPACITY:-8Gi}"
    cacheStorageClassName: "${VOLSYNC_CACHE_SNAPSHOTCLASS:-openebs-hostpath}"
    cacheAccessModes: ["${VOLSYNC_CACHE_ACCESSMODES:-ReadWriteOnce}"]
    storageClassName: "${VOLSYNC_STORAGECLASS:-rook-ceph-block}"
    accessModes: ["${VOLSYNC_ACCESSMODES:-ReadWriteOnce}"]
    moverSecurityContext:
      runAsUser: "${VOLSYNC_UID:-568}"
      runAsGroup: "${VOLSYNC_GID:-568}"
      fsGroup: "${VOLSYNC_GID:-568}"
    retain:
      hourly: 24
      daily: 10
