---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./bjw-s.yaml
  - ./cilium.yaml
  - ./coredns.yaml
  - ./jetstack.yaml
  - ./metrics-server.yaml
  - ./openebs.yaml
  - ./postfinance.yaml
  - ./prometheus-community.yaml
  - ./spegel.yaml
  - ./stakater.yaml
  - ./external-dns.yaml
  - ./ingress-nginx.yaml
  - ./k8s-gateway.yaml
  - ./actions-runner-controller.yaml
  - ./backube.yaml
  - ./cloudnative-pg.yaml
  - ./deliveryheroio.yaml
  - ./descheduler.yaml
  - ./external-secrets.yaml
  - ./grafana.yaml
  - ./kyverno.yaml
  - ./lwolf.yaml
  - ./node-feature-discovery.yaml
  - ./piraeus.yaml
  - ./rook-ceph.yaml
  - ./intel.yaml
  - ./itzg.yaml
