---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - bitnami-charts.yaml
  - cert-manager-linode-webhook-charts-git.yaml
  - coredns-charts.yaml
  - deliveryhero-charts.yaml
  - dex-charts.yaml
  - external-dns-charts.yaml
  - grafana-charts.yaml
  - hajimari-charts.yaml
  - infracloudio-charts.yaml
  - ingress-nginx-charts.yaml
  - jetstack-charts.yaml
  - k8s-at-home-charts.yaml
  - kubernetes-sigs-descheduler-charts.yaml
  - longhorn-charts.yaml
  - lwolf-charts.yaml
  - metallb-charts.yaml
  - node-feature-discovery-charts.yaml
  - oauth2-proxy-charts.yaml
  - prometheus-community-charts.yaml
  - rook-ceph-charts.yaml
  - weaveworks-kured-charts.yaml
