---
kubernetes:
  children:
    master:
      vars:
        ansible_user: wolfgang
        ansible_ssh_port: 22
        ansible_ssh_common_args: -o StrictHostKeyChecking=no
      hosts:
        big-kube-01:
          ansible_host: 172.17.2.1
          rook_block_device: /dev/disk/by-id/ata-Samsung_SSD_840_EVO_250GB_S1DFNEAF307832M
        nuc-kube-01:
          ansible_host: 172.17.2.2
          rook_block_device: /dev/disk/by-id/usb-ASMT_ASM105x_123456797059-0:0
        nuc-kube-02:
          ansible_host: 172.17.2.3
          rook_block_device: /dev/disk/by-id/usb-ASMT_ASM105x_123456797008-0:0
    worker:
      vars:
        ansible_user: wolfgang
        ansible_ssh_port: 22
        ansible_ssh_common_args: -o StrictHostKeyChecking=no
      hosts:
        nuc-kube-03:
          ansible_host: 172.17.2.4
          rook_block_device: /dev/disk/by-id/usb-ASMT_ASM105x_123456797726-0:0
        nuc-kube-04:
          ansible_host: 172.17.2.5
          rook_block_device: /dev/disk/by-id/usb-ASMT_ASM105x_1234567943CF-0:0
