---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: kubereboot
  namespace: flux-system
spec:
  interval: 1h
  url: https://kubereboot.github.io/charts/
  timeout: 3m
