---
title: Dashboard
favicon: https://github.com/walkxcode/dashboard-icons/blob/main/png/homepage.png
theme: dark
color: sky
useEqualHeights: true
headerStyle: clean
iconStyle: theme
statusStyle: dot
#fiveColumns: true
layout:
  Home:
    style: row
    columns: 5
    icon: mdi-home-analytics
  Tools:
    style: row
    columns: 3
    icon: mdi-tools
  Media:
    style: row
    columns: 5
    icon: mdi-play-circle
  Downloads:
    style: row
    columns: 4
    icon: mdi-download-circle
    initiallyCollapsed: true
  Infrastructure:
    style: row
    columns: 4
    icon: mdi-server
    initiallyCollapsed: true
  Storage:
    style: row
    columns: 4
    icon: mdi-desktop-tower
    initiallyCollapsed: true
  Observability:
    style: row
    columns: 4
    icon: mdi-chart-line
    initiallyCollapsed: true
