---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Namespace
  - namespace.yaml
  # Flux kustomizations
  - bazarr/ks.yaml
  - lidarr/ks.yaml
  - overseerr/ks.yaml
  - plex/ks.yaml
  - prowlarr/ks.yaml
  - qbittorrent/ks.yaml
  - radarr/ks.yaml
  - recyclarr/ks.yaml
  - sonarr/ks.yaml
  - tautulli/ks.yaml
